version: '3.8'

services:

  postgres:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-net

  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ca
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "60:80"
    networks:
      - postgres-net

networks:
   postgres-net:
